# Generated by Django 2.1.2 on 2018-10-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0004_auto_20181010_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='invite_person',
            new_name='invite_reason',
        ),
    ]
